### ISSUE TITLE
[Feature] DhcpV6

### ISSUE THREAD

**Issue by Jackbaude** [nispor/mozim#1]
**Problem**
DHCPv6 seems like a necessary addition to this DHCP client.  I would like to make DHCPv6 DORA requests for a [DHCP proxy server](https://github.com/Jackbaude/netavark-dhcp-proxy). The dhcproto crate used to encode and decode DHCP packets seems to support DHCPv6, but I cannot find similar v4 decoding methods under the v6 module.

**Solution**
For the purposes of this crate, a simple boolean argument could be used to determine whether a v6 or v4 connection should be made. Once a lease is defined the implementation of v6 should not be much different than v4.

I would like to help with this issue, but first need some help drawing up what the lease structure would look like.

**Comment by cathay4t** [comment]
For the lease structure, you may refer to RFC 8415 and include include basic properties to get your use case done.

Meanwhile, I hope you should understand the difference between IPv6-RA and DHCPv6: https://blog.grisge.info/posts/ipv6_autoconf_in_linux/

**Comment by cathay4t** [comment]
Hi @Jackbaude I need to do DHCPv6 PD in my gateway, so I am picking up this tasks. Sorry for overlapping. On-going
effort are stored in https://github.com/cathay4t/mozim/tree/dhcpv6
