### ISSUE TITLE
DhcpV4Client trait for async and blocking client

### ISSUE THREAD

**Issue by Jackbaude** [nispor/mozim#17]
The` DhcpV4ClientAsync` does not implement the same methods as `DhcpV4Client`. It would be helpful to have methods such as release_lease on the async version. Is there a way to call these methods on DhcpV4Client or would this be helpful to additionally have these methods on `DhcpV4ClientAsync`. I would be willing to do this if that is the case.

**Comment by cathay4t** [comment]
The underneath implementation is just send out a UDP package and no reply required from DHCP server.

So you may just create a async function to `DhcpV4ClientAsync` without any async stuff in it just to be consistent with `DhcpV4Client`.

I have to admit, this project is crated before rust async become stable, so the fundamental code is not async-aware.
