### ISSUE TITLE
Error when receiving IPv6 multicast packets in raw socket recv

### ISSUE THREAD

**Issue by agorgl** [nispor/mozim#32]
After a dchp (v4) discover packet, when the raw socket `recv` here: https://github.com/nispor/mozim/blob/v0.2.3/src/client.rs#L512 expects a dhcp offer packet but instead receives an IPv6 multicast packet, the following error occurs:
```
InvalidDhcpServerReply: Failed to parse DHCP message from payload of pkg []: parser ran out of data-- not enough bytes
```
This race condition is pretty frequent depending on the existence of such packets.
A more thorough analysis can be found here: https://github.com/containers/netavark/issues/618

**Comment by cathay4t** [comment]
Investigation required to understand why this packet passed the BPF filter.

```
Jul 01 10:27:08 test netavark[3577]: [DEBUG mozim::socket] Raw socket received [51, 51, 0, 0, 0, 22, 118, 255, 172, 65, 53, 143, 134, 221, 96, 0, 0, 0, 0, 36, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 58, 0, 5, 2, 0, 0, 1, 0, 143, 0, 57, 186, 0, 0, 0, 1, 4, 0, 0, 0, 255, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 255, 65, 53, 143]
Jul 01 10:27:08 test netavark[3577]: [ERROR mozim::msg] InvalidDhcpServerReply: Failed to parse DHCP message from payload of pkg []: parser ran out of data-- not enough bytes
```

**Comment by cathay4t** [comment]
@agorgl Could you share the tcpdump/wireshark captured data?

**Comment by cathay4t** [comment]
Above packet has 0x86dd(IPv6), it should dropped by BPF `(BPF_JMP | BPF_JEQ | BPF_K, 0, 8, ETHERTYPE_IP)`.

Pending more investigation.

**Comment by agorgl** [comment]
The problem can be reproduced in some boots consistently, but it seems to be impossible to reproduce in others.
I'm thinking that the problem isn't the packet payload per-se, but maybe at some mozim initializations the bpf filter is not applied at all?

**Comment by cathay4t** [comment]
Aha, the packet is cached by kernel before we applied BPF filter. Let me prepare another patch.

**Comment by cathay4t** [comment]
@agorgl Can you try again with https://github.com/nispor/mozim/pull/35 ?

**Comment by agorgl** [comment]
I'll try to repeat it multiple times and check if `Ignoring invalid DHCP package` shows up, I'll report back soon

**Comment by agorgl** [comment]
I tried this:
```
for i in `seq 1 10`; do
    echo $(date): ROUND $i
    sudo systemctl restart netavark-dhcp-proxy.{socket,service}
    sleep 1
    for j in `seq 1 10`; do
        sleep 3
        echo $(date): retry $j
        sudo systemctl reset-failed sample
        sudo systemctl restart sample
        [ $? -ne 0 ] && break
    done
done
```
across 3 VM reboots, and no `Ignoring invalid DHCP package` showed up, so I believe with #35 we are good to go

**Comment by cathay4t** [comment]
mozim 0.2.4 published. `cargo update` should do the magic to pull it in.
